package controller;

import javafx.fxml.FXML;
import javafx.fxml.FXMLLoader;
import javafx.scene.Scene;
import javafx.stage.Stage;

import java.io.IOException;
import javafx.event.ActionEvent;
import javafx.scene.Node;


public class MainMenuController {
	
	private Stage primaryStage;

	@FXML
	public void startGameClicked(ActionEvent event) throws IOException {
		BackgroundMusicPlayer.stopBackgroundMusic();
		BackgroundMusicPlayer.playBackgroundMusic("/skanja1.wav");
		Scene myScene = FXMLLoader.load(getClass().getResource("/PlayerSelection.fxml"));
		primaryStage = (Stage)((Node)event.getSource()).getScene().getWindow();
		primaryStage.setScene(myScene);
		primaryStage.show();
		primaryStage.setResizable(false);
		primaryStage.setTitle("Player selection");
	}

	@FXML
	public void tutorialClicked(ActionEvent event) {
		// TODO Autogenerated
	}
}