package controller;

import javafx.fxml.FXML;

import javafx.event.ActionEvent;

public class StartGameController {

	// Event Listener on Button.onAction
	@FXML
	public void startGameClicked(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button.onAction
	@FXML
	public void tutorialClicked(ActionEvent event) {
		// TODO Autogenerated
	}
}
